// map-settings — генератор фиксированного порядка отладочных номеров.
// Copyright (C) 2026  Aleksandr Galinskii
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

package main

import (
	"os"
	"regexp"
	"strconv"
	"strings"
)

// dbgOrderPath — файл с зашитым порядком id (append-only).
const dbgOrderPath = "dbgindex_order.go"

var dbgOrderStringRe = regexp.MustCompile(`"((?:[^"\\]|\\.)*)"`)

// readDbgOrder читает существующий порядок id из сгенерированного файла.
func readDbgOrder() []string {
	b, err := os.ReadFile(dbgOrderPath)
	if err != nil {
		return nil
	}
	s := string(b)
	i := strings.Index(s, "var dbgIDOrder = []string{")
	if i < 0 {
		return nil
	}
	s = s[i:]
	var out []string
	for _, m := range dbgOrderStringRe.FindAllStringSubmatch(s, -1) {
		if v, err := strconv.Unquote(`"` + m[1] + `"`); err == nil {
			out = append(out, v)
		}
	}
	return out
}

// writeDbgOrder дополняет порядок новыми id (append-only) и записывает файл.
// Возвращает число добавленных id. Существующие номера не меняются.
func writeDbgOrder() (int, error) {
	existing := readDbgOrder()
	known := map[string]bool{}
	for _, id := range existing {
		known[id] = true
	}
	var structural []string
	seen := map[string]bool{}
	for _, mode := range []string{mapModeTitanator, mapModeDominator} {
		entries, err := structuralDbgEntries(mode)
		if err != nil {
			return 0, err
		}
		for _, e := range entries {
			if seen[e.ID] {
				continue
			}
			seen[e.ID] = true
			structural = append(structural, e.ID)
		}
	}
	added := 0
	for _, id := range structural {
		if known[id] {
			continue
		}
		existing = append(existing, id)
		known[id] = true
		added++
	}
	var b strings.Builder
	b.WriteString("// Code generated by mapsettings -gen-dbgorder; append-only — не менять порядок.\n")
	b.WriteString("// Новые элементы интерфейса дописываются в конец, существующие номера не сдвигаются.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("var dbgIDOrder = []string{\n")
	for _, id := range existing {
		b.WriteString("\t" + strconv.Quote(id) + ",\n")
	}
	b.WriteString("}\n")
	if err := os.WriteFile(dbgOrderPath, []byte(b.String()), 0o644); err != nil {
		return 0, err
	}
	return added, nil
}
